#!/bin/sh

enable_forwarding() {
    sysctl -w net.ipv4.ip_forward=1
    sysctl -w net.ipv6.conf.all.disable_ipv6=1
    sysctl -w net.ipv6.conf.default.disable_ipv6 = 1 
}

setup_pi() {
    echo 0 > /sys/class/leds/led0/brightness
    echo 0 > /sys/class/leds/led1/brightness
    /opt/bin/rpi-fan &
}

setup_ns() {
    ip netns add switch
    ip netns add sanjose
    ip netns add london
    ip netns add milpitas
    ip netns add frontier
    ip netns add starlink
    ip netns add lightsail
}

setup_switch() {
    ip netns exec switch ip link add br0 type bridge
    ip netns exec switch ip link set br0 up

    ip link add veth1 type veth peer name veth1 netns switch
    ip link add veth2 netns sanjose type veth peer name veth2 netns switch
    ip link add veth3 netns london type veth peer name veth3 netns switch
    ip link add veth4 netns milpitas type veth peer name veth4 netns switch
    ip link add veth7 netns frontier type veth peer name veth7 netns switch
    ip link add veth8 netns starlink type veth peer name veth8 netns switch
    ip link add veth10 netns lightsail type veth peer name veth10 netns switch

    ip netns exec switch ip link set veth1 master br0
    ip netns exec switch ip link set veth1 up
    ip netns exec switch ip link set veth2 master br0
    ip netns exec switch ip link set veth2 up
    ip netns exec switch ip link set veth3 master br0
    ip netns exec switch ip link set veth3 up
    ip netns exec switch ip link set veth4 master br0
    ip netns exec switch ip link set veth4 up
    ip netns exec switch ip link set veth7 master br0
    ip netns exec switch ip link set veth7 up
    ip netns exec switch ip link set veth8 master br0
    ip netns exec switch ip link set veth8 up
    ip netns exec switch ip link set veth10 master br0
    ip netns exec switch ip link set veth10 up

    ip addr add 10.0.0.1/24 dev veth1
    ip link set veth1 up
    ip netns exec sanjose ip addr add 10.0.0.2/24 dev veth2
    ip netns exec sanjose ip link set veth2 up
    ip netns exec london ip addr add 10.0.0.3/24 dev veth3
    ip netns exec london ip link set veth3 up
    ip netns exec milpitas ip addr add 10.0.0.4/24 dev veth4
    ip netns exec milpitas ip link set veth4 up
    ip netns exec frontier ip addr add 10.0.0.7/24 dev veth7
    ip netns exec frontier ip link set veth7 up
    ip netns exec starlink ip addr add 10.0.0.8/24 dev veth8
    ip netns exec starlink ip link set veth8 up
    ip netns exec lightsail ip addr add 10.0.0.10/24 dev veth10
    ip netns exec lightsail ip link set veth10 up
}

setup_eth0() {
    ifconfig eth0 192.168.1.2/24
    ifconfig eth0 up

    ip -4 route add 0.0.0.0/0 via 192.168.4.1 dev eth0

    ip link add link eth0 name eth0.2 type vlan id 2
    ip link set eth0.2 netns sanjose
    ip netns exec sanjose ip addr add 192.168.2.1/24 dev eth0.2
    ip netns exec sanjose ip link set eth0.2 up

    ip link add link eth0 name eth0.3 type vlan id 3
    ip link set eth0.3 netns london
    ip netns exec london ip addr add 192.168.3.1/24 dev eth0.3
    ip netns exec london ip link set eth0.3 up

    ip link add link eth0 name eth0.4 type vlan id 4
    ip link set eth0.4 netns milpitas
    ip netns exec milpitas ip addr add 192.168.4.1/24 dev eth0.4
    ip netns exec milpitas ip link set eth0.4 up
    
    ip link add link eth0 name eth0.7 type vlan id 7
    ip link set eth0.7 netns frontier
    ip netns exec frontier ip link set eth0.7 up

    ip link add link eth0 name eth0.8 type vlan id 8
    ip link set eth0.8 netns starlink
    ip netns exec starlink ip link set eth0.8 up
}

setup_routes() {
    ip route add 192.168.2.0/24 via 10.0.0.2
    ip route add 192.168.3.0/24 via 10.0.0.3
    ip route add 192.168.4.0/24 via 10.0.0.4
    ip route add default via 10.0.0.8

    ip netns exec sanjose ip route add 192.168.1.0/24 via 10.0.0.1
    ip netns exec sanjose ip route add default via 10.0.0.8
    ip netns exec london ip route add 192.168.1.0/24 via 10.0.0.1
    ip netns exec london ip route add default via 10.0.0.10
    ip netns exec milpitas ip route add 192.168.1.0/24 via 10.0.0.1
    ip netns exec milpitas ip route add default via 10.0.0.7

    ip netns exec frontier ip route add 192.168.2.0/24 via 10.0.0.2
    ip netns exec frontier ip route add 192.168.3.0/24 via 10.0.0.3
    ip netns exec frontier ip route add 192.168.4.0/24 via 10.0.0.4
    ip netns exec frontier ip route add 10.8.0.2/32 via 10.0.0.10
    
    ip netns exec starlink ip route add 192.168.2.0/24 via 10.0.0.2
    ip netns exec starlink ip route add 192.168.3.0/24 via 10.0.0.3
    ip netns exec starlink ip route add 192.168.4.0/24 via 10.0.0.4
    ip netns exec starlink ip route add 10.8.0.2/32 via 10.0.0.10

    ip netns exec lightsail ip route add 192.168.3.0/24 via 10.0.0.3
    ip netns exec lightsail ip route add default via 10.0.0.8
}

run_dhcpd() {
    rm -f /var/lib/dhcp/dhcpd-*.pid
    touch /var/lib/dhcp/dhcpd-sanjose.leases
    ip netns exec sanjose dhcpd -cf /etc/dhcp/dhcpd-sanjose.conf eth0.2
    touch /var/lib/dhcp/dhcpd-london.leases
    ip netns exec london dhcpd -cf /etc/dhcp/dhcpd-london.conf eth0.3
    touch /var/lib/dhcp/dhcpd-milpitas.leases
    ip netns exec milpitas dhcpd -cf /etc/dhcp/dhcpd-milpitas.conf eth0.4
}

run_dhcpcd() {
    ip netns exec frontier dhcpcd eth0.7
    ip netns exec starlink dhcpcd eth0.8
}

setup_nft() {
    ip netns exec frontier nft -f /etc/nftables-frontier.conf
    ip netns exec starlink nft -f /etc/nftables-starlink.conf
}

start_wg() {
    ip netns exec lightsail ip rule add fwmark 10 table 10
    ip netns exec lightsail nft -f /etc/nftables-ligthsail.conf
    ip netns exec lightsail wg-quick up wg0
}

enable_forwarding
setup_pi
setup_ns
setup_switch
setup_eth0
run_dhcpd
run_dhcpcd
setup_routes
setup_nft
start_wg

while true; do
    sleep 1
done
